// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_rocket

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func RocketResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"code": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"config": schema.MapAttribute{
				ElementType: types.StringType,
				Required:    true,
			},
			"description": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "ID of the Rocket",
				MarkdownDescription: "ID of the Rocket",
			},
			"name": schema.StringAttribute{
				Required: true,
			},
		},
	}
}

type RocketModel struct {
	Code        types.String `tfsdk:"code"`
	Config      types.Map    `tfsdk:"config"`
	Description types.String `tfsdk:"description"`
	Id          types.String `tfsdk:"id"`
	Name        types.String `tfsdk:"name"`
}
