// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_mission

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func MissionResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"description": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"duration": schema.Int64Attribute{
				Required: true,
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "ID of the Mission",
				MarkdownDescription: "ID of the Mission",
			},
			"min_approvers": schema.Int64Attribute{
				Required: true,
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"possible_approvers": schema.ListAttribute{
				ElementType: types.StringType,
				Required:    true,
			},
			"requests": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"rockets": schema.ListAttribute{
				ElementType: types.StringType,
				Required:    true,
			},
		},
	}
}

type MissionModel struct {
	Description       types.String `tfsdk:"description"`
	Duration          types.Int64  `tfsdk:"duration"`
	Id                types.String `tfsdk:"id"`
	MinApprovers      types.Int64  `tfsdk:"min_approvers"`
	Name              types.String `tfsdk:"name"`
	PossibleApprovers types.List   `tfsdk:"possible_approvers"`
	Requests          types.List   `tfsdk:"requests"`
	Rockets           types.List   `tfsdk:"rockets"`
}
