// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider_launchpad

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func LaunchpadProviderSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"api_key": schema.StringAttribute{
				Required: true,
			},
			"endpoint": schema.StringAttribute{
				Required: true,
			},
		},
	}
}

type LaunchpadModel struct {
	ApiKey   types.String `tfsdk:"api_key"`
	Endpoint types.String `tfsdk:"endpoint"`
}
